<a href="https://colab.research.google.com/github/pulindu-seniya-silva/Machine-Learning-and-Optimization-Methods-labs-answers/blob/main/labsheet1_answers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d
print(arr2d[0, 1])


2


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5 ,6])
print(a + b)
print(a * b)
print(a ** 2)

[5 7 9]
[ 4 10 18]
[1 4 9]


In [ ]:
np.zeros((2, 3))
np.ones(4)
np.arange(1, 10, 2)
np.linspace(0, 1, 5)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])